resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/24/4.yaml

packages:
- .

extra-deps:
- xmobar-0.50
- ../../../haskell/mylib/

flags:
 xmobar:
  with_dbus: true
  with_threaded: true
  with_xpm: true
