live_config_reload = false
import = ["~/.config/alacritty/xterm.toml"]

[window]
decorations = "none"
title = "x"

[scrolling]
history = 100000

[font]
normal = { family = "Inconsolata Nerd Font Mono", style = "Bold" }
size = 12

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
blink_timeout = 30
